
version: "3.9"

services:
  postgres_db:
    container_name: timelife_db
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
    volumes:
      - pgdata:/var/lib/postgresql/timelife/data

  redis_db:
    container_name: timelife_redis
    image: redis:7
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/var/lib/redis/timelife/data

volumes:
  pgdata: {}
  cache: {}